### ISSUE TITLE
Weblate duplicated Norwegian translation alerts

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash_import_export_plugins#12]
Hosted Weblate alerts following duplicated Norwegian translation today.
https://hosted.weblate.org/projects/smash/smash-import-and-export-plugins/#alerts
> Weblate could not push changes to the upstream repository.
> ```
> Pull request failed: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.
> ```
> :
> Duplicated translation.
> 
> The component contains several translation files mapped to a single language in Weblate. Please fix this by removing one of the translation files.
> 
> The following occurrences were found:
> 
> Language | Language codes | File names
> -- | -- | --
> Norwegian Bokmål | nb_NO, nb | lib/l10n/intl_nb_NO.arb, lib/l10n/intl_nb.arb

**Comment by sanak** [comment]
I might miss something in PR:https://github.com/geopaparazzi/smash_import_export_plugins/pull/10.
I will check the cause a bit.

**Comment by sanak** [comment]
@moovida Thanks for merge PR:#13 !
Unfortunately, the alert still remains, so further trial will be necessary...
https://hosted.weblate.org/projects/smash/smash-import-and-export-plugins/#alerts

**Comment by moovida** [comment]
This seems to be due to the fact that we have 2 language files, while only one is permitted. We should maybe ask the Norwegian translator to remove one?

**Comment by sanak** [comment]
@moovida Well, dummy `intl_nb.arb` comes from the following issue, so I will delete `intl_nb.arb` once with other PR, then copy some already translated words (for import/export) from SMASH app side Norwegian language.

https://github.com/geopaparazzi/smash/pull/196
> 3. **Add intl_nb.arb for intl_nb_NO.arb fallback**
>    - Similar issue in Every Door: https://github.com/Zverik/every_door/issues/300
>    - Every Door mentions the following step manually in `README.md` - `How To Build` section, but I added empty `intl_nb.arb` file.
>      - https://github.com/Zverik/every_door#how-to-build
>      - > `echo '{}' > lib/l10n/app_zh.arb (fixing Dart's localization issues).
