### ISSUE TITLE
Hosted Weblate shows alert and locked with invalid license

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash_import_export_plugins#4]
https://hosted.weblate.org/projects/smash
![hosted-weblate-smash_import-export_plugins-alert-locked](https://user-images.githubusercontent.com/629923/177232182-e13dae8b-66a8-4452-924c-3ffc071479c6.png)

From clicking alert icon, GitHub<=>Weblate connection seems not to be enough.
https://hosted.weblate.org/projects/smash/smash-import-and-export-plugins/#alerts
![hosted-weblate-smash_import-export_plugins-alert-details](https://user-images.githubusercontent.com/629923/177232312-619600ea-b360-474b-a672-691f9dd75e6d.png)

**Comment by moovida** [comment]
Sorry for the late late reply, I was on leave.

These weblate caos is really bothering. I will see what I can find to solve it.

**Comment by moovida** [comment]
Hi @sanak , I unlocked it, but I can't find the source of the problem, it seemed to be due to a maintainance issue. Let's see if it works now. Else there might be something with the github hooks? I am not sure who did them for the other repo.

**Comment by sanak** [comment]
@moovida Thanks for the response !
The alert and locked icon are still shown, so I think that some more GitHub settings are necessary.

@dkastl Do you remember what was necessary in SMASH main project or other GTT Project ?

**Comment by sanak** [comment]
@moovida  
Well, @dkastl solved the Weblate Manage settings, and it works correctly now, so I close this issue.

**Comment by moovida** [comment]
Thanks a ton guys!!
